import { DatabaseSchema } from "./schema-types";

export function generatePostgreSQL(schema: DatabaseSchema): string {
  let sql = `-- Generated by Visual Schema Designer\n-- Dialect: PostgreSQL\n\n`;

  // Generate Tables
  schema.tables.forEach((table) => {
    sql += `CREATE TABLE "${table.name}" (\n`;
    
    const columnDefs = table.columns.map((col) => {
      let def = `  "${col.name}" ${col.type.toUpperCase()}`;
      
      if (col.isPrimaryKey) def += " PRIMARY KEY";
      if (col.isUnique && !col.isPrimaryKey) def += " UNIQUE";
      if (col.isNotNull && !col.isPrimaryKey) def += " NOT NULL";
      
      return def;
    });

    sql += columnDefs.join(",\n");
    sql += "\n);\n\n";
  });

  // Generate Foreign Keys
  if (schema.relations.length > 0) {
    sql += `-- Relationships\n`;
    schema.relations.forEach((rel) => {
      const fromTable = schema.tables.find(t => t.id === rel.fromTableId);
      const toTable = schema.tables.find(t => t.id === rel.toTableId);
      const fromCol = fromTable?.columns.find(c => c.id === rel.fromColumnId);
      const toCol = toTable?.columns.find(c => c.id === rel.toColumnId);

      if (fromTable && toTable && fromCol && toCol) {
        // Handle 1:1 by adding a UNIQUE constraint on the foreign key column if it's not already unique
        const isOneToOne = rel.type === "1:1";
        const fkName = `fk_${fromTable.name}_${fromCol.name}`;
        
        sql += `ALTER TABLE "${fromTable.name}" ADD CONSTRAINT "${fkName}" `;
        sql += `FOREIGN KEY ("${fromCol.name}") REFERENCES "${toTable.name}" ("${toCol.name}");\n`;
        
        if (isOneToOne) {
          sql += `ALTER TABLE "${fromTable.name}" ADD CONSTRAINT "unique_${fromTable.name}_${fromCol.name}" UNIQUE ("${fromCol.name}");\n`;
        }
      }
    });
  }

  return sql;
}
